
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.22000 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Users/Mike_Wei/program/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.39.33519/bin/Hostx86/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.39.33523 版
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.39.33523.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/Mike_Wei/CLionProjects/MiniTrade/cmake-build-debug/CMakeFiles/3.28.1/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        注意: 包含文件:  C:\\Users\\Mike_Wei\\CLionProjects\\MiniTrade\\cmake-build-debug\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "注意: 包含文件:  "
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Users/Mike_Wei/program/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.39.33519/bin/Hostx86/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.39.33523 版
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.39.33523.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/Mike_Wei/CLionProjects/MiniTrade/cmake-build-debug/CMakeFiles/3.28.1/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        注意: 包含文件:  C:\\Users\\Mike_Wei\\CLionProjects\\MiniTrade\\cmake-build-debug\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "注意: 包含文件:  "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Mike_Wei/CLionProjects/MiniTrade/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-t5xufk"
      binary: "C:/Users/Mike_Wei/CLionProjects/MiniTrade/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-t5xufk"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      VCPKG_APPLOCAL_DEPS: "ON"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "C:/Users/Mike_Wei/program/vcpkg-2024.04.26"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Mike_Wei/CLionProjects/MiniTrade/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-t5xufk'
        
        Run Build Command(s): "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/bin/cmake.exe" -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_ddce2\\fast
        	"C:\\Users\\Mike_Wei\\program\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_ddce2.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_ddce2.dir\\build
        Building C object CMakeFiles/cmTC_ddce2.dir/CMakeCCompilerABI.c.obj
        	"C:\\Program Files\\JetBrains\\CLion 2024.1.1\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_ddce2.dir\\CMakeCCompilerABI.c.obj.d --working-dir=C:\\Users\\Mike_Wei\\CLionProjects\\MiniTrade\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-t5xufk --filter-prefix="注意: 包含文件:  " -- C:\\Users\\Mike_Wei\\program\\MICROS~1\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx86\\x64\\cl.exe @C:\\Users\\Mike_Wei\\AppData\\Local\\Temp\\nm58B1.tmp
        CMakeCCompilerABI.c
        注意: 包含文件:  C:\\Program Files\\JetBrains\\CLion 2024.1.1\\bin\\cmake\\win\\x64\\share\\cmake-3.28\\Modules\\CMakeCompilerABI.h
        Linking C executable cmTC_ddce2.exe
        	"C:\\Program Files\\JetBrains\\CLion 2024.1.1\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_ddce2.dir --rc=C:\\WINDOW~1\\10\\bin\\100226~1.0\\x86\\rc.exe --mt=C:\\WINDOW~1\\10\\bin\\100226~1.0\\x86\\mt.exe --manifests -- C:\\Users\\Mike_Wei\\program\\MICROS~1\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx86\\x64\\link.exe /nologo @CMakeFiles\\cmTC_ddce2.dir\\objects1.rsp @C:\\Users\\Mike_Wei\\AppData\\Local\\Temp\\nm592F.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_ddce2.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_ddce2.dir/embed.manifest
        RC Pass 1:
        C:\\WINDOW~1\\10\\bin\\100226~1.0\\x86\\rc.exe /fo CMakeFiles\\cmTC_ddce2.dir/manifest.res CMakeFiles\\cmTC_ddce2.dir/manifest.rc
        LINK Pass 1:
        C:\\Users\\Mike_Wei\\program\\MICROS~1\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx86\\x64\\link.exe /nologo @CMakeFiles\\cmTC_ddce2.dir\\objects1.rsp /out:cmTC_ddce2.exe /implib:cmTC_ddce2.lib /pdb:C:\\Users\\Mike_Wei\\CLionProjects\\MiniTrade\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-t5xufk\\cmTC_ddce2.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_ddce2.dir/intermediate.manifest CMakeFiles\\cmTC_ddce2.dir/manifest.res
        MT:
        C:\\WINDOW~1\\10\\bin\\100226~1.0\\x86\\mt.exe /nologo /manifest CMakeFiles\\cmTC_ddce2.dir/intermediate.manifest /out:CMakeFiles\\cmTC_ddce2.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\WINDOW~1\\10\\bin\\100226~1.0\\x86\\rc.exe /fo CMakeFiles\\cmTC_ddce2.dir/manifest.res CMakeFiles\\cmTC_ddce2.dir/manifest.rc
        FINAL LINK:
        C:\\Users\\Mike_Wei\\program\\MICROS~1\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx86\\x64\\link.exe /nologo @CMakeFiles\\cmTC_ddce2.dir\\objects1.rsp /out:cmTC_ddce2.exe /implib:cmTC_ddce2.lib /pdb:C:\\Users\\Mike_Wei\\CLionProjects\\MiniTrade\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-t5xufk\\cmTC_ddce2.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_ddce2.dir/intermediate.manifest CMakeFiles\\cmTC_ddce2.dir/manifest.res
        	C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noprofile -executionpolicy Bypass -file C:/Users/Mike_Wei/program/vcpkg-2024.04.26/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/Mike_Wei/CLionProjects/MiniTrade/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-t5xufk/cmTC_ddce2.exe -installedDir C:/Users/Mike_Wei/program/vcpkg-2024.04.26/installed/x64-windows/debug/bin -OutVariable out
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/Mike_Wei/CLionProjects/MiniTrade/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ooeocf"
      binary: "C:/Users/Mike_Wei/CLionProjects/MiniTrade/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ooeocf"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      VCPKG_APPLOCAL_DEPS: "ON"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "C:/Users/Mike_Wei/program/vcpkg-2024.04.26"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Mike_Wei/CLionProjects/MiniTrade/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ooeocf'
        
        Run Build Command(s): "C:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/bin/cmake.exe" -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_a65b9\\fast
        	"C:\\Users\\Mike_Wei\\program\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_a65b9.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_a65b9.dir\\build
        Building CXX object CMakeFiles/cmTC_a65b9.dir/CMakeCXXCompilerABI.cpp.obj
        	"C:\\Program Files\\JetBrains\\CLion 2024.1.1\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_a65b9.dir\\CMakeCXXCompilerABI.cpp.obj.d --working-dir=C:\\Users\\Mike_Wei\\CLionProjects\\MiniTrade\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-ooeocf --filter-prefix="注意: 包含文件:  " -- C:\\Users\\Mike_Wei\\program\\MICROS~1\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx86\\x64\\cl.exe @C:\\Users\\Mike_Wei\\AppData\\Local\\Temp\\nm5E7E.tmp
        CMakeCXXCompilerABI.cpp
        注意: 包含文件:  C:\\Program Files\\JetBrains\\CLion 2024.1.1\\bin\\cmake\\win\\x64\\share\\cmake-3.28\\Modules\\CMakeCompilerABI.h
        Linking CXX executable cmTC_a65b9.exe
        	"C:\\Program Files\\JetBrains\\CLion 2024.1.1\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_a65b9.dir --rc=C:\\WINDOW~1\\10\\bin\\100226~1.0\\x86\\rc.exe --mt=C:\\WINDOW~1\\10\\bin\\100226~1.0\\x86\\mt.exe --manifests -- C:\\Users\\Mike_Wei\\program\\MICROS~1\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx86\\x64\\link.exe /nologo @CMakeFiles\\cmTC_a65b9.dir\\objects1.rsp @C:\\Users\\Mike_Wei\\AppData\\Local\\Temp\\nm5F0B.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_a65b9.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_a65b9.dir/embed.manifest
        RC Pass 1:
        C:\\WINDOW~1\\10\\bin\\100226~1.0\\x86\\rc.exe /fo CMakeFiles\\cmTC_a65b9.dir/manifest.res CMakeFiles\\cmTC_a65b9.dir/manifest.rc
        LINK Pass 1:
        C:\\Users\\Mike_Wei\\program\\MICROS~1\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx86\\x64\\link.exe /nologo @CMakeFiles\\cmTC_a65b9.dir\\objects1.rsp /out:cmTC_a65b9.exe /implib:cmTC_a65b9.lib /pdb:C:\\Users\\Mike_Wei\\CLionProjects\\MiniTrade\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-ooeocf\\cmTC_a65b9.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_a65b9.dir/intermediate.manifest CMakeFiles\\cmTC_a65b9.dir/manifest.res
        MT:
        C:\\WINDOW~1\\10\\bin\\100226~1.0\\x86\\mt.exe /nologo /manifest CMakeFiles\\cmTC_a65b9.dir/intermediate.manifest /out:CMakeFiles\\cmTC_a65b9.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\WINDOW~1\\10\\bin\\100226~1.0\\x86\\rc.exe /fo CMakeFiles\\cmTC_a65b9.dir/manifest.res CMakeFiles\\cmTC_a65b9.dir/manifest.rc
        FINAL LINK:
        C:\\Users\\Mike_Wei\\program\\MICROS~1\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx86\\x64\\link.exe /nologo @CMakeFiles\\cmTC_a65b9.dir\\objects1.rsp /out:cmTC_a65b9.exe /implib:cmTC_a65b9.lib /pdb:C:\\Users\\Mike_Wei\\CLionProjects\\MiniTrade\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-ooeocf\\cmTC_a65b9.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_a65b9.dir/intermediate.manifest CMakeFiles\\cmTC_a65b9.dir/manifest.res
        	C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noprofile -executionpolicy Bypass -file C:/Users/Mike_Wei/program/vcpkg-2024.04.26/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/Mike_Wei/CLionProjects/MiniTrade/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ooeocf/cmTC_a65b9.exe -installedDir C:/Users/Mike_Wei/program/vcpkg-2024.04.26/installed/x64-windows/debug/bin -OutVariable out
        
      exitCode: 0
...
